---
- name: ensure student is qualified to have an account
  hosts: teng1.eng.tlap.redhat.com
  tasks:
    - name: REST call to ensure (1) have signed authorization, (2) in 3rd grade or higher, (3) student active
      uri:
        url: http://teng1.eng.tlap.redhat.com
        return_content: yes
      register: results
      
    - name: print all results
      debug:
        var: results
        
    - name: print the content from the uri
      debug:
        var: results.content
        
    - name: fail execution of the module if "False" is returned
      fail:
      when: "'False' in results.content"
