---
- name: ensure student is qualified to have an account
  hosts: teng1.eng.tlap.redhat.com
  tasks:
    - name: REST call to ensure (1) have signed authorization, (2) in 3rd grade or higher, (3) student active
      uri:
        url: http://http://teng1.eng.tlap.redhat.com
        return_content: True
      register: results
      
    - name: print results
      debug:
        var: results
